#spring.application.name=ranaswanu
#
#
#spring.datasource.url=jdbc:sqlserver://;serverName=localhost;database=test;encrypt=true;trustServerCertificate=true;port=1433;
#spring.datasource.username=sa
#spring.datasource.password=Rasintha2002@
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update