-- PostgreSQL schema = the FINAL result of the 18 old SQL Server migrations (src/main/resources/db/migration).
-- BIT -> BOOLEAN, DATETIME2 -> TIMESTAMP, NVARCHAR -> VARCHAR, IDENTITY -> GENERATED BY DEFAULT AS IDENTITY.

CREATE TABLE users
(
    user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50)  NOT NULL UNIQUE,
    email           VARCHAR(100) NOT NULL UNIQUE,
    password_hash   VARCHAR(256) NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active       BOOLEAN   DEFAULT TRUE,
    role            VARCHAR(50),
    profile_picture VARCHAR(255),
    address         VARCHAR(255),
    phone_number    VARCHAR(255)
);
CREATE INDEX ix_users_created_at ON users (created_at);

CREATE TABLE password_reset_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(255) NOT NULL UNIQUE,
    user_id     BIGINT       NOT NULL REFERENCES users (user_id),
    expiry_date TIMESTAMP    NOT NULL,
    used        BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE farm_activities
(
    activity_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity        VARCHAR(500) NOT NULL,
    activity_status BOOLEAN   DEFAULT TRUE,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id         BIGINT       NOT NULL REFERENCES users (user_id)
);

CREATE TABLE expenses
(
    expense_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    title        VARCHAR(50) NOT NULL,
    category     VARCHAR(50) NOT NULL,
    amount       BIGINT      NOT NULL,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id      BIGINT      NOT NULL REFERENCES users (user_id)
);

CREATE TABLE reminders
(
    reminder_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reminder_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description   VARCHAR(500),
    created_at    TIMESTAMP          DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP          DEFAULT CURRENT_TIMESTAMP,
    user_id       BIGINT    NOT NULL REFERENCES users (user_id)
);

CREATE TABLE notifications
(
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message         VARCHAR(255) NOT NULL,
    title           VARCHAR(50)  NOT NULL,
    is_read         BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    user_id         BIGINT       NOT NULL REFERENCES users (user_id)
);

CREATE TABLE deliveries
(
    delivery_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_status         VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    assigned_date           TIMESTAMP            DEFAULT CURRENT_TIMESTAMP,
    estimated_delivery_date TIMESTAMP,
    actual_delivery_date    TIMESTAMP,
    delivery_note           VARCHAR(500),
    created_at              TIMESTAMP            DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP            DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transportation_requests
(
    transportation_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description               VARCHAR(500),
    pickup_location           VARCHAR(255) NOT NULL,
    delivery_location         VARCHAR(255) NOT NULL,
    requested_date_time       TIMESTAMP    NOT NULL,
    vehicle_type              VARCHAR(50)  NOT NULL,
    estimated_weight          BIGINT       NOT NULL,
    request_status            VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    special_instructions      VARCHAR(500),
    size                      VARCHAR(50)  NOT NULL,
    request_type              VARCHAR(20)  NOT NULL DEFAULT 'FARMER_REQUEST',
    created_at                TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    user_id                   BIGINT       NOT NULL REFERENCES users (user_id),
    delivery_id               BIGINT REFERENCES deliveries (delivery_id)
);

CREATE TABLE orders
(
    order_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date_time  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    order_status     VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    notes            VARCHAR(255),
    total_amount     NUMERIC(18, 2) NOT NULL DEFAULT 0.00,
    contact_number   VARCHAR(50)    NOT NULL,
    delivery_address VARCHAR(255)   NOT NULL,
    payment_method   VARCHAR(100)   NOT NULL,
    payment_status   VARCHAR(20)    NOT NULL DEFAULT 'UNPAID',
    created_at       TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    user_id          BIGINT         NOT NULL REFERENCES users (user_id),
    delivery_id      BIGINT REFERENCES deliveries (delivery_id)
);

CREATE TABLE customer_reviews
(
    review_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    description VARCHAR(500) NOT NULL,
    rating      INT          NOT NULL CHECK (rating BETWEEN 1 AND 5),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id     BIGINT       NOT NULL REFERENCES users (user_id),
    reviewer_id BIGINT REFERENCES users (user_id),
    order_id    BIGINT REFERENCES orders (order_id)
);
-- One rating per order (old rows have no order, so only non-null values must be unique)
CREATE UNIQUE INDEX ux_reviews_order ON customer_reviews (order_id) WHERE order_id IS NOT NULL;

CREATE TABLE product_listings
(
    list_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_status         BOOLEAN        NOT NULL DEFAULT FALSE,
    available_stock        NUMERIC(18, 2) NOT NULL DEFAULT 0.00,
    price_per_unit         NUMERIC(18, 2) NOT NULL DEFAULT 0.00,
    minimum_order_quantity NUMERIC(18, 2) NOT NULL DEFAULT 0.00,
    harvested_date         TIMESTAMP,
    delivery_option        VARCHAR(255)   NOT NULL,
    description            VARCHAR(500),
    unit_of_measurement    VARCHAR(10)    NOT NULL,
    category               VARCHAR(255)   NOT NULL,
    product_name           VARCHAR(255)   NOT NULL,
    product_image          VARCHAR(255),
    created_at             TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    user_id                BIGINT         NOT NULL REFERENCES users (user_id),
    admin_disabled         BOOLEAN        NOT NULL DEFAULT FALSE,
    admin_disabled_at      TIMESTAMP,
    location               VARCHAR(100)
);
CREATE INDEX ix_product_listings_created_at ON product_listings (created_at);

CREATE TABLE order_items
(
    item_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity   NUMERIC(18, 2) NOT NULL,
    unit_price NUMERIC(18, 2) NOT NULL,
    subtotal   NUMERIC(18, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    order_id   BIGINT         NOT NULL REFERENCES orders (order_id),
    list_id    BIGINT         NOT NULL REFERENCES product_listings (list_id)
);

CREATE TABLE locations
(
    user_id    BIGINT PRIMARY KEY REFERENCES users (user_id),
    latitude   NUMERIC(10, 7)  NOT NULL,
    longitude  NUMERIC(10, 7)  NOT NULL,
    accuracy   NUMERIC(18, 2)  NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chats
(
    chat_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_one_id BIGINT NOT NULL REFERENCES users (user_id),
    user_two_id BIGINT NOT NULL REFERENCES users (user_id),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_chats_user_one_user_two UNIQUE (user_one_id, user_two_id)
);

CREATE TABLE messages
(
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    VARCHAR(1000) NOT NULL,
    is_read    BOOLEAN       NOT NULL DEFAULT FALSE,
    sent_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id    BIGINT        NOT NULL REFERENCES users (user_id),
    chat_id    BIGINT        NOT NULL REFERENCES chats (chat_id) ON DELETE CASCADE
);

CREATE TABLE live_stocks
(
    live_stock_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category      VARCHAR(100) NOT NULL,
    breed         VARCHAR(100),
    amount        BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    user_id       BIGINT       NOT NULL REFERENCES users (user_id)
);

CREATE TABLE crops
(
    crop_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_name        VARCHAR(255)   NOT NULL,
    category         VARCHAR(100)   NOT NULL,
    unit             VARCHAR(50)    NOT NULL,
    harvest_quantity NUMERIC(18, 2) NOT NULL DEFAULT 0.00,
    harvest_date     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes            VARCHAR(1000),
    created_at       TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
    user_id          BIGINT         NOT NULL REFERENCES users (user_id)
);

CREATE TABLE field_plots
(
    field_plot_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    current_crop     VARCHAR(255) NOT NULL,
    crop_variety     VARCHAR(255) NOT NULL,
    area_unit        NUMERIC(18, 2),
    growth_stage     VARCHAR(100) NOT NULL,
    health_condition VARCHAR(100) NOT NULL,
    field_logs       TEXT,
    inspection_date  DATE         NOT NULL DEFAULT CURRENT_DATE,
    created_at       TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    user_id          BIGINT       NOT NULL REFERENCES users (user_id),
    crop_id          BIGINT REFERENCES crops (crop_id)
);

CREATE TABLE support_messages
(
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject    VARCHAR(100)  NOT NULL,
    message    VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id    BIGINT        NOT NULL REFERENCES users (user_id)
);
CREATE INDEX ix_support_messages_created_at ON support_messages (created_at);
