CREATE TABLE chats
(
    chat_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_one_id BIGINT NOT NULL,
    user_two_id BIGINT NOT NULL,
    created_at  TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at  TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    CONSTRAINT fk_chats_userone
        FOREIGN KEY (user_one_id) REFERENCES users (user_id),
    CONSTRAINT fk_chats_usertwo
        FOREIGN KEY (user_two_id) REFERENCES users (user_id),
    CONSTRAINT uq_chats_userone_usertwo
        UNIQUE (user_one_id, user_two_id)
);

CREATE TABLE messages
(
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    VARCHAR(1000) NOT NULL,
    is_read    BOOLEAN       NOT NULL DEFAULT FALSE,
    sent_at    TIMESTAMP     NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    user_id    BIGINT        NOT NULL,
    chat_id    BIGINT        NOT NULL,
    CONSTRAINT fk_messages_users
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_messages_chats
        FOREIGN KEY (chat_id) REFERENCES chats (chat_id) ON DELETE CASCADE
);

CREATE TABLE live_stocks
(
    live_stock_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category      VARCHAR(100) NOT NULL,
    breed         VARCHAR(100),
    amount        BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at    TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    user_id       BIGINT       NOT NULL,
    CONSTRAINT fk_livestocks_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE crops
(
    crop_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_name        VARCHAR(255)   NOT NULL,
    category         VARCHAR(100)   NOT NULL,
    unit             VARCHAR(50)    NOT NULL,
    harvest_quantity DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
    harvest_date     TIMESTAMP      NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    notes            VARCHAR(1000),
    created_at       TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at       TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    user_id          BIGINT         NOT NULL,
    CONSTRAINT fk_crops_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE field_plots
(
    field_plot_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    current_crop     VARCHAR(255) NOT NULL,
    crop_variety     VARCHAR(255) NOT NULL,
    area_unit        DECIMAL(18, 2),
    growth_stage     VARCHAR(100) NOT NULL,
    health_condition VARCHAR(100) NOT NULL,
    field_logs       TEXT,
    inspection_date  DATE         NOT NULL DEFAULT CURRENT_DATE,
    created_at       TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at       TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    user_id          BIGINT       NOT NULL,
    crop_id          BIGINT       NOT NULL,
    CONSTRAINT fk_fieldplots_users
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_fieldplots_crops
        FOREIGN KEY (crop_id) REFERENCES crops (crop_id)
);
