CREATE TABLE support_messages
(
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject    VARCHAR(100)  NOT NULL,
    message    VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    user_id    BIGINT        NOT NULL,
    CONSTRAINT fk_support_messages_users FOREIGN KEY (user_id) REFERENCES users (user_id)
);
