CREATE TABLE delivery_vehicles
(
    vehicle_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_name        VARCHAR(100) NOT NULL,
    vehicle_type        VARCHAR(50)  NOT NULL,
    registration_number VARCHAR(50)  NOT NULL,
    capacity_kg         BIGINT       NOT NULL,
    is_active           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at          TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    user_id             BIGINT       NOT NULL,
    CONSTRAINT fk_delivery_vehicles_users
        FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE UNIQUE INDEX ux_delivery_vehicles_registration_number
    ON delivery_vehicles (registration_number);

ALTER TABLE deliveries
    ADD COLUMN vehicle_id BIGINT NULL;

ALTER TABLE deliveries
    ADD CONSTRAINT fk_deliveries_vehicles
        FOREIGN KEY (vehicle_id) REFERENCES delivery_vehicles (vehicle_id)
            ON DELETE SET NULL;

ALTER TABLE transportation_requests
    ADD COLUMN order_id BIGINT NULL;

ALTER TABLE transportation_requests
    ADD CONSTRAINT fk_transportation_requests_orders
        FOREIGN KEY (order_id) REFERENCES orders (order_id)
            ON DELETE SET NULL;
