CREATE TABLE users
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    email         VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(256) NOT NULL,
    created_at    TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    is_active     BOOLEAN   DEFAULT TRUE
);

-- PostgreSQL compares text case-sensitively (SQL Server did not).
-- These indexes stop two accounts that differ only by letter case (Test@x.com / test@x.com).
CREATE UNIQUE INDEX ux_users_email_lower ON users (LOWER(email));
CREATE UNIQUE INDEX ux_users_username_lower ON users (LOWER(username));
