-- Replace the single-role model with a user <-> roles many-to-many model.
-- The legacy users.role column is intentionally retained for backward compatibility.

CREATE TABLE IF NOT EXISTS roles
(
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50) NOT NULL,
    CONSTRAINT uq_roles_name UNIQUE (name)
);

INSERT INTO roles (name) VALUES ('BUYER') ON CONFLICT (name) DO NOTHING;
INSERT INTO roles (name) VALUES ('FARMER') ON CONFLICT (name) DO NOTHING;
INSERT INTO roles (name) VALUES ('TRANSPORT') ON CONFLICT (name) DO NOTHING;
INSERT INTO roles (name) VALUES ('ADMIN') ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS user_roles
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id)
        REFERENCES roles (role_id) ON DELETE CASCADE
);

-- Backfill the role previously stored in users.role.
INSERT INTO user_roles (user_id, role_id)
SELECT u.user_id, r.role_id
FROM users u
         JOIN roles r ON r.name = UPPER(TRIM(u.role))
WHERE u.role IS NOT NULL
  AND NOT EXISTS (SELECT 1
                  FROM user_roles ur
                  WHERE ur.user_id = u.user_id
                    AND ur.role_id = r.role_id);

-- Farmers and transport partners are also buyers in the new capability model.
INSERT INTO user_roles (user_id, role_id)
SELECT u.user_id, r.role_id
FROM users u
         JOIN roles r ON r.name = 'BUYER'
WHERE UPPER(TRIM(u.role)) IN ('FARMER', 'TRANSPORT')
  AND NOT EXISTS (SELECT 1
                  FROM user_roles ur
                  WHERE ur.user_id = u.user_id
                    AND ur.role_id = r.role_id);
