CREATE TABLE farm_activities
(
    activity_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity        VARCHAR(500) NOT NULL,
    activity_status BOOLEAN   DEFAULT TRUE,
    created_at      TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at      TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    user_id         BIGINT       NOT NULL,
    CONSTRAINT fk_farm_activity
        FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE expenses
(
    expense_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_date TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    title        VARCHAR(50) NOT NULL,
    category     VARCHAR(50) NOT NULL,
    amount       BIGINT      NOT NULL, -- change to numeric if needed
    created_at   TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at   TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    user_id      BIGINT      NOT NULL,
    CONSTRAINT fk_expenses
        FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE customer_reviews
(
    review_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_date TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    description VARCHAR(500) NOT NULL,
    rating      INT          NOT NULL CHECK (rating BETWEEN 1 AND 5),
    created_at  TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at  TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    user_id     BIGINT       NOT NULL,
    CONSTRAINT fk_customer_review
        FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE reminders
(
    reminder_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reminder_date TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    description   VARCHAR(500),
    created_at    TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at    TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    user_id       BIGINT    NOT NULL,
    CONSTRAINT fk_reminder
        FOREIGN KEY (user_id) REFERENCES users (user_id)
);
