CREATE TABLE notifications
(
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message         VARCHAR(255) NOT NULL,
    title           VARCHAR(50)  NOT NULL,
    is_read         BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    user_id         BIGINT       NOT NULL,
    CONSTRAINT fk_notifications
        FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE deliveries
(
    delivery_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_status         BOOLEAN NOT NULL DEFAULT FALSE,
    assigned_date           TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    estimated_delivery_date TIMESTAMP,
    actual_delivery_date    TIMESTAMP,
    delivery_note           VARCHAR(500),
    created_at              TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at              TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC')
);

CREATE TABLE transportation_requests
(
    transportation_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description               VARCHAR(500),
    pickup_location           VARCHAR(255) NOT NULL,
    delivery_location         VARCHAR(255) NOT NULL,
    requested_date_time       TIMESTAMP    NOT NULL,
    vehicle_type              VARCHAR(50)  NOT NULL,
    estimated_weight          BIGINT       NOT NULL,
    request_status            BOOLEAN      NOT NULL DEFAULT FALSE,
    special_instructions      VARCHAR(500),
    size                      VARCHAR(50)  NOT NULL,
    created_at                TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at                TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    user_id                   BIGINT       NOT NULL,
    delivery_id               BIGINT       NOT NULL,
    CONSTRAINT fk_transportation_requests_users
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_transportation_requests_deliveries
        FOREIGN KEY (delivery_id) REFERENCES deliveries (delivery_id)
);

CREATE TABLE orders
(
    order_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date_time  TIMESTAMP      NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    order_status     BOOLEAN        NOT NULL DEFAULT FALSE,
    notes            VARCHAR(255),
    total_amount     DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
    contact_number   VARCHAR(50)    NOT NULL,
    delivery_address VARCHAR(255)   NOT NULL,
    payment_method   VARCHAR(100)   NOT NULL,
    payment_status   BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at       TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    user_id          BIGINT         NOT NULL,
    delivery_id      BIGINT         NOT NULL,
    CONSTRAINT fk_orders_users
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_orders_deliveries
        FOREIGN KEY (delivery_id) REFERENCES deliveries (delivery_id)
);
