CREATE TABLE product_listings
(
    list_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_status         BOOLEAN        NOT NULL DEFAULT FALSE,
    available_stock        DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
    price_per_unit         DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
    minimum_order_quantity DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
    harvested_date         TIMESTAMP,
    delivery_option        VARCHAR(255)   NOT NULL,
    description            VARCHAR(500),
    unit_of_measurement    VARCHAR(10)    NOT NULL,
    category               VARCHAR(255)   NOT NULL,
    product_name           VARCHAR(255)   NOT NULL,
    product_image          VARCHAR(255),
    created_at             TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at             TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    user_id                BIGINT         NOT NULL,
    CONSTRAINT fk_product_listings
        FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE order_items
(
    item_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity   DECIMAL(18, 2) NOT NULL,
    unit_price DECIMAL(18, 2) NOT NULL,
    subtotal   DECIMAL(18, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    order_id   BIGINT         NOT NULL,
    list_id    BIGINT         NOT NULL,
    CONSTRAINT fk_order_items_orders
        FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT fk_order_items_product_listings
        FOREIGN KEY (list_id) REFERENCES product_listings (list_id)
);

CREATE TABLE locations
(
    user_id    BIGINT PRIMARY KEY,
    latitude   DECIMAL(10, 7)  NOT NULL,
    longitude  DECIMAL(10, 7)  NOT NULL,
    accuracy   DECIMAL(18, 2)  NOT NULL,
    created_at TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP DEFAULT (NOW() AT TIME ZONE 'UTC'),
    CONSTRAINT fk_locations
        FOREIGN KEY (user_id) REFERENCES users (user_id)
);
